// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Idempotency struct {
	IdemKey   string
	Request   []byte
	Response  []byte
	CreatedAt pgtype.Timestamptz
	Ttl       pgtype.Timestamptz
}

type OpsCase struct {
	CaseID     pgtype.UUID
	TenantID   int64
	Title      string
	Severity   interface{}
	Status     string
	ResourceID pgtype.Int8
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	Labels     []byte
}

type Outbox struct {
	ID          int64
	Aggregate   pgtype.Text
	AggregateID pgtype.Text
	Topic       pgtype.Text
	Payload     []byte
	CreatedAt   pgtype.Timestamptz
	Published   pgtype.Bool
	PublishedAt pgtype.Timestamptz
}
