// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type ActionsAudit struct {
	ID         int64
	IncidentID sql.NullInt64
	Step       sql.NullInt32
	Action     sql.NullString
	Params     pqtype.NullRawMessage
	Dryrun     sql.NullBool
	Result     pqtype.NullRawMessage
	Ts         sql.NullTime
}

type HotServices1m struct {
	Tb      interface{}
	Service sql.NullString
	AvgVal  float64
	Rk      int64
}

type Incident struct {
	ID          int64
	Fingerprint sql.NullString
	Service     sql.NullString
	Status      sql.NullString
	Sev         sql.NullInt32
	Hypothesis  pqtype.NullRawMessage
	Plan        pqtype.NullRawMessage
	CreatedAt   sql.NullTime
	ClosedAt    sql.NullTime
}

type Metrics1m struct {
	Tb      interface{}
	Metric  string
	Service sql.NullString
	AvgVal  float64
	MaxVal  interface{}
}

type MetricsPoint struct {
	Ts      time.Time
	Metric  string
	Service sql.NullString
	Labels  pqtype.NullRawMessage
	Value   float64
}
